migrate root ca from 0.2.x
Start9Labs/embassy-os pull request #1074
Opened 2022-01-14 20:05 UTC by ProofOfKeags

2022-01-17 21:15 UTC, dr-bonez requested changes
the root ca needs to be included in the return type instead of manually importing it. the recovery flow already accounts for importing CAs and tor addresses

2022-01-17 21:15 UTC, dr-bonez commented on appmgr/src/setup.rs
> +        tokio::fs::read(root_ca_cert_path)
this probably doesn't afford any speedup.

2022-01-17 22:39 UTC, ProofOfKeags commented
I don't understand what you mean by this. The ticket is cut on the assumption that it didn't account for this. So which is it? Is the ticket invalid? or do we need to include this change?

2022-01-17 22:55 UTC, dr-bonez commented
for 0.3.0 backup recovery, this *is* accounted for. it just isn't for 0.2.x. the 0.2.x recovery just needs to splice its tor address and cert into that existing code

2022-01-17 23:53 UTC, dr-bonez approved these changes

2022-01-20 02:09 UTC, ProofOfKeags commented
closed in favor of #1105

2022-01-20 02:09 UTC, closed without merging