marketplace url in server.update
Start9Labs/embassy-os pull request #1189
Opened 2022-02-10 17:29 UTC by DrewAns

send marketplace url to server.update

2022-02-10 17:31 UTC, dr-bonez requested changes

2022-02-10 17:31 UTC, dr-bonez commented on frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
> +      })
why on restartServer

2022-02-10 17:34 UTC, dr-bonez submitted a review, later dismissed

2022-02-10 20:46 UTC, MattDHill submitted a review, later dismissed

2022-02-10 23:06 UTC, DrewAns commented
@ProofOfKeags No, this is requests from aiden that came in today and had no ticket

2022-02-11 04:32 UTC, dr-bonez approved these changes

2022-02-11 04:32 UTC, merged