Feature/script packing
Start9Labs/embassy-os pull request #1435
Opened 2022-05-10 22:47 UTC by ProofOfKeags

2022-05-11 21:24 UTC, ProofOfKeags commented
This is ready for review now

2022-05-16 21:06 UTC, ProofOfKeags commented
![bernie-PR](https://user-images.githubusercontent.com/4033651/168682585-b898872f-9824-4cc2-9d7a-0e97813b9357.jpg)

2022-05-16 21:15 UTC, dr-bonez requested changes

2022-05-16 21:15 UTC, dr-bonez commented on backend/src/install/cleanup.rs
> +        .join(version.as_str());
I think there's a function `assets_dir` in volumes.rs that would be better to use for this

2022-05-16 21:15 UTC, dr-bonez commented on backend/src/install/cleanup.rs
> +        .join(version.as_str());
This path is incorrect

2022-05-16 21:15 UTC, dr-bonez commented on backend/src/s9pk/header.rs
> +        };
```suggestion
    self.scripts.unwrap_or_default().serialize_entry("scripts", &mut writer)?;
```

2022-05-16 22:11 UTC, dr-bonez approved these changes

2022-05-16 22:11 UTC, merged