Feat/js action
Start9Labs/embassy-os pull request #1437
Opened 2022-05-11 18:27 UTC by Blu-J

2022-05-18 18:00 UTC, ProofOfKeags reviewed
Reviewed as best I could, I think it should also be reviewed by @dr-bonez

2022-05-19 19:02 UTC, dr-bonez requested changes

2022-05-19 19:03 UTC, dr-bonez commented
Also, refactor the script packing / unpacking code to use the constant you added

2022-05-19 20:15 UTC, Blu-J commented on backend/build-prod.sh
> +alias 'rust-arm64-builder'='docker run --rm -it -v "$HOME/.cargo/registry":/root/.cargo/registry -v "$(pwd)":/home/rust/src -P start9/rust-arm-cross:aarch64'
Will clean up, was using it for debugging

2022-05-19 20:18 UTC, Blu-J commented on backend/test/js_action_execute/package-data/scripts/test-package/0.3.0.3/types.d.ts
> +export type Effects = {
No, just for the writers to know our api

2022-05-19 20:23 UTC, Blu-J commented on backend/src/manager/mod.rs
> +        PackageProcedure::Script(_) => return Ok(()),
Solved by using NonDetachingJoinHandle

2022-05-19 22:06 UTC, Blu-J commented on backend/test/js_action_execute/package-data/scripts/test-package/0.3.0.3/types.d.ts
> +export type Effects = {
Yes sorry, I think they do since the embassy.d.ts imports this, sorry had to think.

2022-05-19 22:07 UTC, Blu-J commented on backend/src/procedure/js_scripts.rs
> +    pub struct JsFunctionInformation {
Not even used anymore, thanks for pointing this out

2022-05-19 22:15 UTC, Blu-J commented on backend/src/procedure/js_scripts.rs
> +                }),
Main is entry point, it is the loader. So renaming to loadModule

2022-05-19 22:17 UTC, Blu-J commented on backend/src/procedure/mod.rs
> +            ProcedureName::Action(id) => Some(format!("{}Action", id)),
So, after talking with @dr-bonez Thanks for the idea
We are going with the js using json pointers
As for the docker, this is the old code, what it already was. Not sure we can change it now.

2022-05-19 22:35 UTC, Blu-J commented on backend/src/procedure/js_scripts.rs
> +                    .join("embassy.js");
Asking aiden, the best guess was that the path is the wrong name, and should have been the data_dir.
Changed, and also made the input be impl AsRef<Path>

2022-05-20 00:02 UTC, dr-bonez approved these changes

2022-05-20 00:02 UTC, merged