Update contribution and frontend readme
Start9Labs/embassy-os pull request #1467
Opened 2022-05-28 04:20 UTC by BBlackwo

Changes:
- Add syntax highlighting to code blocks
- Make heading casing consistent (see https://github.com/Start9Labs/embassy-os/pull/1463#discussion_r883889676)
- Add marketplace to frontend readme
- change `build:deps` script to use `npm ci` (to make consistent with the [setup instructions](https://github.com/Start9Labs/embassy-os/blob/master/frontend/README.md?plain=1#L35))

2022-06-01 21:03 UTC, elvece commented on frontend/package.json
> +    "build:deps": "rm -rf .angular/cache && cd ../patch-db/client && npm ci && npm run build",
👍

2022-06-01 21:03 UTC, elvece requested changes
Small copy suggestion for accuracy, otherwise looks good, thanks!

2022-06-01 23:06 UTC, BBlackwo commented on frontend/README.md
> +1. **marketplace**: ui to browse, install, and update packaged services
Updated :+1: Thanks for the better copy!

2022-06-03 02:24 UTC, BBlackwo commented
Hi @elvece, I fixed up that marketplace copy if you can have another look. Thanks!

2022-06-03 18:26 UTC, elvece approved these changes

2022-06-03 18:26 UTC, merged