Http proxy
Start9Labs/embassy-os pull request #1772
Opened 2022-08-31 00:34 UTC by redragonx

2022-09-15 20:01 UTC, dr-bonez commented on backend/src/net/proxy_controller.rs
> +                                    let mapping = docker_service_mapping.read_owned().await;
```suggestion
                                    let mapping = docker_service_mapping.read().await;
```

2022-09-16 00:52 UTC, redragonx commented on backend/src/net/proxy_controller.rs
> +    async fn new(listener_addr: SocketAddr) -> Result<Self, Error> {
Server::bind requires a SocketAddr with an IP and the port to bind to. So should `new` accept the IpAddr and a u16 for the port?

2022-11-06 16:45 UTC, dr-bonez requested changes

2022-11-07 03:47 UTC, redragonx commented on backend/src/backup/restore.rs
> +            NetController::setup_embassy_ui(rpc_ctx.clone()).await?;
Do you have a way to activate that? So I can test.

2022-11-07 03:49 UTC, redragonx commented on backend/src/bin/avahi-alias.rs
> -            eprintln!("Published {:?}", lan_address_ptr);
ok

2022-11-07 03:53 UTC, redragonx commented on backend/src/error.rs
> -    Nginx = 16,
ok

2022-11-09 05:30 UTC, dr-bonez approved these changes

2022-11-09 05:30 UTC, merged