Appmgr readme update
Start9Labs/embassy-os pull request #298
Opened 2021-03-29 18:38 UTC by kn0wmad

2021-03-30 14:41 UTC, dr-bonez requested changes
`toml-cli` is a dependency for hello-world, not appmgr

2021-03-30 15:54 UTC, kn0wmad commented
Oops, fixed.

2021-03-30 16:55 UTC, kn0wmad commented
Done

2021-04-02 19:48 UTC, dr-bonez approved these changes

2021-04-02 19:49 UTC, merged