Feature/ssh
Start9Labs/embassy-os pull request #382
Opened 2021-07-27 22:38 UTC by ProofOfKeags

2021-07-27 22:42 UTC, ProofOfKeags commented on appmgr/src/ssh.rs
> +    // if not in DB, Err404
consider synchronizing the db and keys file regardless of success or failure here.

2021-07-27 22:42 UTC, ProofOfKeags commented on appmgr/src/ssh.rs
> +        sync_keys_from_db(pool, Path::new(SSH_AUTHORIZED_KEYS_FILE)).await?;
consider synchronizing even if the key is a duplicate.

2021-07-28 05:07 UTC, kn0wmad reviewed
Just observing

2021-07-30 21:02 UTC, dr-bonez requested changes

2021-08-05 18:01 UTC, merged