Feature/server metrics
Start9Labs/embassy-os pull request #405
Opened 2021-08-11 23:22 UTC by ProofOfKeags

merge after #401

2021-08-12 13:50 UTC, kn0wmad reviewed
Observing

2021-08-12 17:19 UTC, dr-bonez requested changes

2021-08-12 17:19 UTC, dr-bonez commented on appmgr/src/system.rs
> +        let fs_res = nix::sys::statfs::statfs("/").map_err(|e| Error {
use Error::new

2021-08-12 17:19 UTC, dr-bonez commented on appmgr/src/system.rs
> +        if entry.starts_with("MemTotal") {
use match guards

2021-08-12 17:21 UTC, dr-bonez commented on appmgr/src/system.rs
> +    match (*metrics_val).clone() {
```suggestion
    match metrics_val.clone() {
```

2021-08-13 21:39 UTC, ProofOfKeags commented
Ready for re-review

2021-08-17 23:32 UTC, merged