adds avahi base service to init function of mdns controller
Start9Labs/embassy-os pull request #407
Opened 2021-08-13 21:38 UTC by ProofOfKeags

2021-08-17 23:49 UTC, ProofOfKeags commented on appmgr/src/net/mdns.rs
> +                    5959,
```suggestion
                    443,
```

2021-08-17 23:49 UTC, ProofOfKeags commented on appmgr/src/net/mdns.rs
> +                    hostname_raw,
```suggestion
                    std::ptr::null(),
```

2021-08-17 23:49 UTC, ProofOfKeags commented
Add hostnamectl change to startup sequence

2021-08-18 23:29 UTC, ProofOfKeags commented
ready for re-review

2021-08-19 17:41 UTC, dr-bonez requested changes

2021-08-19 17:41 UTC, dr-bonez commented on appmgr/src/bin/embassy-init.rs
> +    embassy::hostname::ensure_correct_hostname().await?;
```suggestion
    embassy::hostname::sync_hostname().await?;
```

2021-08-19 17:41 UTC, dr-bonez commented on appmgr/src/hostname.rs
> +pub async fn ensure_correct_hostname() -> Result<(), Error> {
```suggestion
pub async fn sync_hostname() -> Result<(), Error> {
```

2021-08-19 17:42 UTC, dr-bonez approved these changes

2021-08-19 17:42 UTC, merged