cifs for cloud backups on lan
Start9Labs/embassy-os pull request #799
Opened 2021-11-15 05:09 UTC by MattDHill

2021-11-15 17:50 UTC, DrewAns commented on setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.html
> +        id="passwword"
two w's.  Also should the type of this input be password so its ******

2021-11-15 17:50 UTC, DrewAns commented on setup-wizard/src/app/pages/recover/recover.page.ts
> +      drives.filter(d => d.partitions.length).forEach(d => {
maybe a good place for a map?

2021-11-30 19:58 UTC, dr-bonez requested changes

2021-12-04 21:39 UTC, dr-bonez requested changes

2021-12-04 22:09 UTC, MattDHill commented on setup-wizard/src/app/services/api/api.service.ts
> +  abstract verifyCifs (cifs: VerifyCifs): Promise<EmbassyOSRecoveryInfo> // echo - throws error if invalid
This is a outdated comment on the abstract class. The actual method being hit currently is `setup.cifs.check`, as seen in live-api.service.ts. I can change to `steup.cifs.verify` if you prefer.

2021-12-04 22:09 UTC, MattDHill commented on setup-wizard/src/app/services/api/api.service.ts
> +  abstract verify03XPassword (source: RecoverySource, password: string): Promise<boolean> // setup.recovery.test-password
Tech debt. Will delete.

2021-12-04 22:10 UTC, MattDHill commented on setup-wizard/src/app/services/api/api.service.ts
> +  abstract verifyCifs (cifs: VerifyCifs): Promise<EmbassyOSRecoveryInfo> // echo - throws error if invalid
Is this still valid?

`abstract verifyProductKey (): Promise<void> // echo - throws error if invalid`

2021-12-05 06:07 UTC, closed without merging